### ISSUE TITLE
chore: Add an Attractive ToDo App

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SyedImtiyaz-1/GetTechProjects#593]
**Describe the bug**
I will add an attractive todo app .

**Screenshots**
![Screenshot 2024-06-02 173918](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/118350936/bab164b8-d84b-4c68-951f-7a63cd96cc52)

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali
